<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Hash;

class UsuarioSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        DB::table('usuario')->insert([
            [
                'usuario'            => 'claudio.sanhueza',
                'nombre'             => 'Claudio',
                'primer_apellido'    => 'Sanhueza',
                'segundo_apellido'   => 'Soto',
                'correo_electronico' => 'claudio.sanhueza@mineduc.cl',
                'password'           => Hash::make('123456789'),
                'cod_departamento'   => 1,
                'cod_usuario'        => 1,
                'cod_estado_usuario' => 1,
                'created_at'         => now(),
                'updated_at'         => now(),
            ],
            [
                'usuario'            => 'adolfo.quinteros',
                'nombre'             => 'Adolfo',
                'primer_apellido'    => 'Quinteros',
                'segundo_apellido'   => ' ',
                'correo_electronico' => 'adolfo.quiteros@mineduc.cl',
                'password'           => Hash::make('123456789'),
                'cod_departamento'   => 1,
                'cod_usuario'        => 23,
                'cod_estado_usuario' => 1,
                'created_at'         => now(),
                'updated_at'         => now(),
            ],
            [
                'usuario'            => 'nicolas.borgono',
                'nombre'             => 'Nicolás',
                'primer_apellido'    => 'Borgoño',
                'segundo_apellido'   => 'Becerra',
                'correo_electronico' => 'nicolas.borgoño@mineduc.cl',
                'password'           => Hash::make('123456789'),
                'cod_departamento'   => 5,
                'cod_usuario'        => 2,
                'cod_estado_usuario' => 1,
                'created_at'         => now(),
                'updated_at'         => now(),
            ],
            [
                'usuario'            => 'ariel.torrealba',
                'nombre'             => 'Ariel',
                'primer_apellido'    => 'Torrealba',
                'segundo_apellido'   => 'Orellana',
                'correo_electronico' => 'ariel.torrealba@mineduc.cl',
                'password'           => Hash::make('123456789'),
                'cod_departamento'   => 2,
                'cod_usuario'        => 3,
                'cod_estado_usuario' => 1,
                'created_at'         => now(),
                'updated_at'         => now(),
            ],
            [
                'usuario'            => 'camila.vasquez',
                'nombre'             => 'Camila',
                'primer_apellido'    => 'Vásquez',
                'segundo_apellido'   => 'Zúñiga',
                'correo_electronico' => 'camila.vasquez@mineduc.cl',
                'password'           => Hash::make('123456789'),
                'cod_departamento'   => 4,
                'cod_usuario'        => 4,
                'cod_estado_usuario' => 1,
                'created_at'         => now(),
                'updated_at'         => now(),
            ],
            [
                'usuario'            => 'regis.yanez',
                'nombre'             => 'Regis',
                'primer_apellido'    => 'Yánez',
                'segundo_apellido'   => 'Álvarez',
                'correo_electronico' => 'regis.yanez@mineduc.cl',
                'password'           => Hash::make('123456789'),
                'cod_departamento'   => 1,
                'cod_usuario'        => 5,
                'cod_estado_usuario' => 1,
                'created_at'         => now(),
                'updated_at'         => now(),
            ],
            [
                'usuario'            => 'hans.sprohnle',
                'nombre'             => 'Hans',
                'primer_apellido'    => 'Spröhnle',
                'segundo_apellido'   => 'Orellana',
                'correo_electronico' => 'hans.sprohnle@mineduc.cl',
                'password'           => Hash::make('123456789'),
                'cod_departamento'   => 6,
                'cod_usuario'        => 6,
                'cod_estado_usuario' => 1,
                'created_at'         => now(),
                'updated_at'         => now(),
            ],
            [
                'usuario'            => 'camila.montero',
                'nombre'             => 'Camila',
                'primer_apellido'    => 'Montero',
                'segundo_apellido'   => 'Cid',
                'correo_electronico' => 'camila.montero@mineduc.cl',
                'password'           => Hash::make('123456789'),
                'cod_departamento'   => 7,
                'cod_usuario'        => 7,
                'cod_estado_usuario' => 1,
                'created_at'         => now(),
                'updated_at'         => now(),
            ],
            [
                'usuario'            => 'marcela.cortes',
                'nombre'             => 'Marcela',
                'primer_apellido'    => 'Cortés',
                'segundo_apellido'   => 'Adasme',
                'correo_electronico' => 'marcela.cortes@mineduc.cl',
                'password'           => Hash::make('123456789'),
                'cod_departamento'   => 7,
                'cod_usuario'        => 8,
                'cod_estado_usuario' => 1,
                'created_at'         => now(),
                'updated_at'         => now(),
            ],
            [
                'usuario'            => 'claudia.mancilla',
                'nombre'             => 'Claudia',
                'primer_apellido'    => 'Mancilla',
                'segundo_apellido'   => 'Matus de la Parra',
                'correo_electronico' => 'claudia.mancilla@mineduc.cl',
                'password'           => Hash::make('123456789'),
                'cod_departamento'   => 8,
                'cod_usuario'        => 9,
                'cod_estado_usuario' => 1,
                'created_at'         => now(),
                'updated_at'         => now(),
            ],
            [
                'usuario'            => 'jimena.sanhueza',
                'nombre'             => 'Jimena',
                'primer_apellido'    => 'Sanhueza',
                'segundo_apellido'   => 'Martínez',
                'correo_electronico' => 'jimena.sanhueza@mineduc.cl',
                'password'           => Hash::make('123456789'),
                'cod_departamento'   => 8,
                'cod_usuario'        => 10,
                'cod_estado_usuario' => 1,
                'created_at'         => now(),
                'updated_at'         => now(),
            ],
            [
                'usuario'            => 'felipe.arriet',
                'nombre'             => 'Felipe',
                'primer_apellido'    => 'Arriet',
                'segundo_apellido'   => 'Pacheco',
                'correo_electronico' => 'felipe.arriet@mineduc.cl',
                'password'           => Hash::make('123456789'),
                'cod_departamento'   => 9,
                'cod_usuario'        => 11,
                'cod_estado_usuario' => 1,
                'created_at'         => now(),
                'updated_at'         => now(),
            ],
            [
                'usuario'            => 'valeria.castañeda',
                'nombre'             => 'Valeria',
                'primer_apellido'    => 'Castañeda',
                'segundo_apellido'   => 'Vera',
                'correo_electronico' => 'valeria.castañeda@mineduc.cl',
                'password'           => Hash::make('123456789'),
                'cod_departamento'   => 10,
                'cod_usuario'        => 12,
                'cod_estado_usuario' => 1,
                'created_at'         => now(),
                'updated_at'         => now(),
            ],
            [
                'usuario'            => 'daniel.jara',
                'nombre'             => 'Daniel',
                'primer_apellido'    => 'Jara',
                'segundo_apellido'   => 'Baginsky',
                'correo_electronico' => 'daniel.jara@mineduc.cl',
                'password'           => Hash::make('123456789'),
                'cod_departamento'   => 14,
                'cod_usuario'        => 13,
                'cod_estado_usuario' => 1,
                'created_at'         => now(),
                'updated_at'         => now(),
            ],
            [
                'usuario'            => 'macarena.calderon',
                'nombre'             => 'Macarena',
                'primer_apellido'    => 'Calderon',
                'segundo_apellido'   => 'Guiñez',
                'correo_electronico' => 'macarena.calderon@mineduc.cl',
                'password'           => Hash::make('123456789'),
                'cod_departamento'   => 14,
                'cod_usuario'        => 14,
                'cod_estado_usuario' => 1,
                'created_at'         => now(),
                'updated_at'         => now(),
            ],
            [
                'usuario'            => 'jonathan.ojeda',
                'nombre'             => 'Jonathan',
                'primer_apellido'    => 'Ojeda',
                'segundo_apellido'   => 'Campos',
                'correo_electronico' => 'jonathan.ojeda@mineduc.cl',
                'password'           => Hash::make('123456789'),
                'cod_departamento'   => 15,
                'cod_usuario'        => 15,
                'cod_estado_usuario' => 1,
                'created_at'         => now(),
                'updated_at'         => now(),
            ],
            [
                'usuario'            => 'sebastian.solis',
                'nombre'             => 'Sebastián',
                'primer_apellido'    => 'Solís',
                'segundo_apellido'   => 'Rojas',
                'correo_electronico' => 'sebastian.solis@mineduc.cl',
                'password'           => Hash::make('123456789'),
                'cod_departamento'   => 16,
                'cod_usuario'        => 16,
                'cod_estado_usuario' => 1,
                'created_at'         => now(),
                'updated_at'         => now(),
            ],
            [
                'usuario'            => 'jaime.bravo',
                'nombre'             => 'Jaime',
                'primer_apellido'    => 'Bravo',
                'segundo_apellido'   => 'Munita',
                'correo_electronico' => 'jaime.bravo@mineduc.cl',
                'password'           => Hash::make('123456789'),
                'cod_departamento'   => 16,
                'cod_usuario'        => 17,
                'cod_estado_usuario' => 1,
                'created_at'         => now(),
                'updated_at'         => now(),
            ],
            [
                'usuario'            => 'macarena.noguera',
                'nombre'             => 'Macarena',
                'primer_apellido'    => 'Noguera',
                'segundo_apellido'   => 'Osorio',
                'correo_electronico' => 'macarena.noguera@mineduc.cl',
                'password'           => Hash::make('123456789'),
                'cod_departamento'   => 17,
                'cod_usuario'        => 18,
                'cod_estado_usuario' => 1,
                'created_at'         => now(),
                'updated_at'         => now(),
            ],
            [
                'usuario'            => 'johanna.bascur',
                'nombre'             => 'Johanna',
                'primer_apellido'    => 'Bascur',
                'segundo_apellido'   => 'González',
                'correo_electronico' => 'johanna.bascur@mineduc.cl',
                'password'           => Hash::make('123456789'),
                'cod_departamento'   => 11,
                'cod_usuario'        => 19,
                'cod_estado_usuario' => 1,
                'created_at'         => now(),
                'updated_at'         => now(),
            ],
            [
                'usuario'            => 'ivan.tobar',
                'nombre'             => 'Iván',
                'primer_apellido'    => 'Tobar',
                'segundo_apellido'   => 'Ortiz',
                'correo_electronico' => 'ivan.tobar@mineduc.cl',
                'password'           => Hash::make('123456789'),
                'cod_departamento'   => 12,
                'cod_usuario'        => 20,
                'cod_estado_usuario' => 1,
                'created_at'         => now(),
                'updated_at'         => now(),
            ],
            [
                'usuario'            => 'victoria.parra',
                'nombre'             => 'Victoria',
                'primer_apellido'    => 'Parra',
                'segundo_apellido'   => 'Moreno',
                'correo_electronico' => 'victoria.parra@mineduc.cl',
                'password'           => Hash::make('123456789'),
                'cod_departamento'   => 2,
                'cod_usuario'        => 21,
                'cod_estado_usuario' => 1,
                'created_at'         => now(),
                'updated_at'         => now(),
            ],
            [
                'usuario'            => 'renzo.molina',
                'nombre'             => 'Renzo',
                'primer_apellido'    => 'Molina',
                'segundo_apellido'   => 'Pardo',
                'correo_electronico' => 'renzo.pardo@mineduc.cl',
                'password'           => Hash::make('123456789'),
                'cod_departamento'   => 6,
                'cod_usuario'        => 22,
                'cod_estado_usuario' => 1,
                'created_at'         => now(),
                'updated_at'         => now(),
            ],
        ]);
    }
}
